/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kreditkm;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author T430
 */
public class mainMenu extends javax.swing.JFrame {
    JPanel Kredit, inputPelanggan, Cash, dataMotor, dataCash, dataKredit, dataPelanggan, Cicilan, dataMotor2;
    JFrame laporan;
    void switchPanel(JPanel panel) {
        pnlUtama.removeAll();
        pnlUtama.add(panel);
        pnlUtama.revalidate();
        pnlUtama.repaint();
       
    }
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        Kredit = new beliKredit();
        Cash = new beliCash();
        inputPelanggan = new inputPelanggan();
        dataPelanggan = new pnlPelanggan();
        dataMotor = new pnlMotor();
        dataCash = new pnlDataCash();
        dataKredit = new pnlDataKredit();
        Cicilan = new cicilan();
        dataMotor2 = new pnlMotor2();
        laporan = new formLaporan();
        pnlUtama.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        cicilan = new model.KButton();
        inputpelanggan = new model.KButton();
        pnlUtama = new javax.swing.JLayeredPane();
        kGradientPanel2 = new model.KGradientPanel();
        kGradientPanel3 = new model.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        datapelanggan = new model.KButton();
        motor = new model.KButton();
        datacash = new model.KButton();
        datakredit = new model.KButton();
        jLabel2 = new javax.swing.JLabel();
        belicash = new model.KButton();
        belikredit = new model.KButton();
        kButton1 = new model.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(79, 138, 139));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cicilan.setText("CICILAN");
        cicilan.setkBorderRadius(40);
        cicilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicilanActionPerformed(evt);
            }
        });
        jLayeredPane1.add(cicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 150, 40));

        inputpelanggan.setText("TAMBAH PELANGGAN");
        inputpelanggan.setkBorderRadius(40);
        inputpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpelangganActionPerformed(evt);
            }
        });
        jLayeredPane1.add(inputpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 150, 40));

        pnlUtama.setBackground(new java.awt.Color(251, 212, 109));
        pnlUtama.setMaximumSize(new java.awt.Dimension(770, 420));
        pnlUtama.setMinimumSize(new java.awt.Dimension(770, 420));
        pnlUtama.setOpaque(true);
        pnlUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jLayeredPane1.add(pnlUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 770, 420));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jLayeredPane1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 820, 400));

        kGradientPanel3.setkEndColor(new java.awt.Color(79, 138, 139));
        kGradientPanel3.setkStartColor(new java.awt.Color(244, 246, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("MENU UTAMA");

        datapelanggan.setText("DATA PELANGGAN");
        datapelanggan.setkBorderRadius(40);
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });

        motor.setText("DATA MOTOR");
        motor.setkBorderRadius(40);
        motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorActionPerformed(evt);
            }
        });

        datacash.setText("DATA CASH");
        datacash.setkBorderRadius(40);
        datacash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datacashActionPerformed(evt);
            }
        });

        datakredit.setText("DATA KREDIT");
        datakredit.setkBorderRadius(40);
        datakredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datakreditActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/menu.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(datakredit, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datacash, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(motor, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(datapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(datapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datacash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(datakredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLayeredPane1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        belicash.setText("BELI CASH");
        belicash.setkBorderRadius(40);
        belicash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belicashActionPerformed(evt);
            }
        });
        jLayeredPane1.add(belicash, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 150, 40));

        belikredit.setText("BELI KREDIT");
        belikredit.setkBorderRadius(40);
        belikredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belikreditActionPerformed(evt);
            }
        });
        jLayeredPane1.add(belikredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 150, 40));

        kButton1.setText("LAPORAN");
        kButton1.setkBorderRadius(40);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpelangganActionPerformed
        switchPanel(inputPelanggan);
    }//GEN-LAST:event_inputpelangganActionPerformed

    private void belicashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belicashActionPerformed
        switchPanel(Cash);
    }//GEN-LAST:event_belicashActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed
        switchPanel(dataPelanggan);
    }//GEN-LAST:event_datapelangganActionPerformed

    private void motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorActionPerformed
        switchPanel(dataMotor2);
    }//GEN-LAST:event_motorActionPerformed

    private void datacashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datacashActionPerformed
        switchPanel(dataCash);
    }//GEN-LAST:event_datacashActionPerformed

    private void datakreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datakreditActionPerformed
        switchPanel(dataKredit);
    }//GEN-LAST:event_datakreditActionPerformed

    private void belikreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belikreditActionPerformed
        switchPanel(Kredit);
    }//GEN-LAST:event_belikreditActionPerformed

    private void cicilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicilanActionPerformed
        switchPanel(Cicilan);
    }//GEN-LAST:event_cicilanActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        laporan.setVisible(true);
    }//GEN-LAST:event_kButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(Exception e){
            System.err.println("Failed Installing Theme");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private model.KButton belicash;
    private model.KButton belikredit;
    private model.KButton cicilan;
    private model.KButton datacash;
    private model.KButton datakredit;
    private model.KButton datapelanggan;
    private model.KButton inputpelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private model.KButton kButton1;
    private model.KGradientPanel kGradientPanel2;
    private model.KGradientPanel kGradientPanel3;
    private model.KButton motor;
    private javax.swing.JLayeredPane pnlUtama;
    // End of variables declaration//GEN-END:variables
}
