/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kreditkm;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.DB;
/**
 *
 * @author T430
 */
public class pnlDataCash extends javax.swing.JPanel {
    
     
    /**
     * Creates new form pnlPelanggan
     */
    public pnlDataCash() {
        initComponents();
        datacash();
        
    }
    
    private void datacash() {
        String[] judul={"Kode Cash","Tanggal Cash","Kode Pelanggan","Kode Motor","Jumlah Beli","Bayar","Kembalian","Keterangan"}; 
        DefaultTableModel tabModel = new DefaultTableModel (null,judul);
            try {
                DB db = new DB ("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
                db.createQuery("Select * from belicash order by kodecash");
                while (db.getResult().next()) {
                    String kodecash_p = db.getResult().getString("kodecash");
                    String tglcash = db.getResult().getString("tanggalcash");
                    String kodepelanggan = db.getResult().getString("kodecust");
                    String kodemotor = db.getResult().getString("kodemotor");
                    String jumlah = db.getResult().getString("jumlah");
                    String bayar = db.getResult().getString("bayar");
                    String kembalii = db.getResult().getString("kembali");
                    String keterangan = db.getResult().getString("keterangan");
            
                    Object[] data = {kodecash_p,tglcash,kodepelanggan,kodemotor,jumlah,bayar,kembalii,keterangan};
                    tabModel.addRow(data);
                    //getAutoKodePelanggan();
                }
                db.closeResult();
                db.closeConnection();
        
                tablecash.setModel(tabModel);
                
                tablecash.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD, 12));
                tablecash.getTableHeader().setOpaque(false);
                tablecash.getTableHeader().setBackground(new Color(251,253,138));
                tablecash.setRowHeight(25);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                for(int a=0;a<tablecash.getColumnCount();a++){
                    tablecash.getColumnModel().getColumn(a).setCellRenderer(centerRenderer);
                }
                scrolldatacash.getViewport().add(tablecash);
                scrolldatacash.setViewportView(tablecash);
                }
                catch (Exception ex) {
                     System.out.println(ex); 
                }
    }
    
    void refresh(){
        kodecash.setText("CASH-");
        tglbelicash.setText("00/00/0000");
        kodecust.setText("CUST-");
        namaplg.setText("_____________");
        kodemotor.setText("MTR-");
        namamtr.setText("_____________");
        jmlbeli.setText("000");
        bayar.setText("000");
        kembali.setText("000");
        tharga.setText("000");
        ket.setText("______________");
        txtcari.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new model.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        scrolldatacash = new javax.swing.JScrollPane();
        tablecash = new javax.swing.JTable();
        hapus = new model.KButton();
        refresh = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        kGradientPanel2 = new model.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodecust = new javax.swing.JLabel();
        tglbelicash = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        namaplg = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kodemotor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        namamtr = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jmlbeli = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bayar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kodecash = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tharga = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 105, 114));
        setMaximumSize(new java.awt.Dimension(770, 420));
        setMinimumSize(new java.awt.Dimension(770, 420));
        setPreferredSize(new java.awt.Dimension(770, 420));

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(1, 169, 180));
        kGradientPanel1.setkStartColor(new java.awt.Color(135, 223, 214));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA PEMBELIAN CASH");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablecash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablecash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecashMouseClicked(evt);
            }
        });
        scrolldatacash.setViewportView(tablecash);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(251, 253, 138));
        kGradientPanel2.setkStartColor(new java.awt.Color(135, 223, 214));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("TANGGAL BELI CASH");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("KODE PELANGGAN");

        kodecust.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kodecust.setText("CUST-");

        tglbelicash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tglbelicash.setText("00/00/0000");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("NAMA PELANGGAN");

        namaplg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaplg.setText("_____________");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("KODE MOTOR");

        kodemotor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kodemotor.setText("MTR-");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("NAMA MOTOR");

        namamtr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namamtr.setText("_____________");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("JUMLAH BELI");

        jmlbeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmlbeli.setText("000");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("BAYAR");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Rp.");

        bayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bayar.setText("000");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("KETERANGAN");

        ket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ket.setText("______________");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("KODE CASH");

        kodecash.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kodecash.setText("CASH-");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("KEMBALIAN");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Rp.");

        kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kembali.setText("000");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("TOTAL HARGA");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Rp.");

        tharga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tharga.setText("000");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(87, 87, 87)
                                .addComponent(kodecash))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)
                                .addComponent(tglbelicash)))
                        .addGap(32, 32, 32)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(61, 61, 61)
                                .addComponent(namamtr))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(61, 61, 61)
                                .addComponent(kodemotor))))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(43, 43, 43)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodecust)
                            .addComponent(namaplg))))
                .addGap(44, 44, 44)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(65, 65, 65)
                        .addComponent(jmlbeli))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(ket))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14))
                                .addGap(36, 36, 36)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel18)))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kodecash)
                            .addComponent(jLabel11)
                            .addComponent(kodemotor))
                        .addGap(17, 17, 17)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tglbelicash)
                            .addComponent(jLabel12)
                            .addComponent(namamtr)))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jmlbeli))
                        .addGap(13, 13, 13)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(tharga))))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kodecust))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(namaplg))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(bayar))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(kembali))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ket))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrolldatacash)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh)
                    .addComponent(cari)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrolldatacash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablecashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecashMouseClicked
        Object a = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 0);
        Object b = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 1);
        Object c = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 2);
        Object d = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 3);
        Object e = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 4);
        Object f = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 5);
        Object g = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 6);
        Object p = tablecash.getModel().getValueAt(tablecash.getSelectedRow(), 7);
        kodecash.setText(a.toString());
        tglbelicash.setText(b.toString());
        kodecust.setText(c.toString());
        kodemotor.setText(d.toString());
        jmlbeli.setText(e.toString());
        bayar.setText(f.toString());
        kembali.setText(g.toString());
        ket.setText(p.toString());
        
        try {
            DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
            db.createQuery("select belicash.total, pelanggan.nama, motor.namamotor, belicash.kodecash from motor,pelanggan,belicash "
                    + "where belicash.kodecust=pelanggan.kodecust "
                    + "AND belicash.kodemotor=motor.kodemotor "
                    + "AND belicash.kodecash = '"+kodecash.getText()+"'");
            while(db.getResult().next()){
                String h = db.getResult().getString("nama");
                String i = db.getResult().getString("namamotor");
                String j = db.getResult().getString("total");
                namaplg.setText(h);
                namamtr.setText(i);
                tharga.setText(j);
            }
            
            datacash();
            txtcari.setText("");
            db.closeResult();
            db.closeConnection();
        } catch (Exception ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_tablecashMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
            db.createUpdate("Delete from belicash where kodecash = '"+kodecash.getText()+"'");
            String pesan = ("Data Pembelian " +kodecash.getText()+ " Telah Dihapus!");
            JOptionPane.showMessageDialog(kGradientPanel1, pesan);
            
            db.closeResult();
            db.closeConnection();
            datacash();
            refresh();
        }catch (Exception se){
            System.out.println(se);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        refresh();
        datacash();
    }//GEN-LAST:event_refreshActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        String[] judul={"Kode Cash","Tanggal Cash","Kode Pelanggan","Kode Motor","Jumlah Beli","Bayar","Kembali","Keterangan"};
        DefaultTableModel tabModel = new DefaultTableModel (null,judul);
        try {
            DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
            db.createQuery("select * from belicash where "
                + "tanggalcash like '%"+txtcari.getText()+"%'"
                + "OR kodecust like '%"+txtcari.getText()+"%'"
                + "OR kodemotor like '%"+txtcari.getText()+"%'"
                + "OR jumlah like '%"+txtcari.getText()+"%'"
                + "OR bayar like'%"+txtcari.getText()+"%'"
                + "OR kembali like '%"+txtcari.getText()+"%'"
                + "OR keterangan like '%"+txtcari.getText()+"%'"
                + "OR kodecash like '%"+txtcari.getText()+"%'");
            while (db.getResult().next()) {
                String kodepelanggan = db.getResult().getString("kodecust");
                String tglcash = db.getResult().getString("tanggalcash");
                String kodecashh = db.getResult().getString("kodecash");
                String kodemtr = db.getResult().getString("kodemotor");
                String jumlah = db.getResult().getString("jumlah");
                String bayarr = db.getResult().getString("bayar");
                String kembalii = db.getResult().getString("kembali");
                String kett = db.getResult().getString("keterangan");

                Object[] data = {kodecashh,tglcash,kodepelanggan,kodemtr,jumlah,bayarr,kembalii,kett};
                tabModel.addRow(data);
            }
            db.closeResult();
            db.closeConnection();
            
            tablecash.setModel(tabModel);
            scrolldatacash.getViewport().add(tablecash);
            scrolldatacash.setViewportView(tablecash);
        }
        catch (Exception se) {
            System.out.println(se);
        }
    }//GEN-LAST:event_cariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayar;
    private javax.swing.JButton cari;
    private model.KButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jmlbeli;
    private model.KGradientPanel kGradientPanel1;
    private model.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel kodecash;
    private javax.swing.JLabel kodecust;
    private javax.swing.JLabel kodemotor;
    private javax.swing.JLabel namamtr;
    private javax.swing.JLabel namaplg;
    private javax.swing.JButton refresh;
    private javax.swing.JScrollPane scrolldatacash;
    private javax.swing.JTable tablecash;
    private javax.swing.JLabel tglbelicash;
    private javax.swing.JLabel tharga;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
