/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kreditkm;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.DB;

/**
 *
 * @author T430
 */
public class pnlMotor2 extends javax.swing.JPanel {
    

    /**
     * Creates new form pnlkredit2
     */
    public pnlMotor2() {
        initComponents();
        datamotor();
        getAutoKode();
    }
    
    void getAutoKode(){
        try{
                    DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
                    db.createQuery("select * from motor");
                    if(db.getResult().next()){
                        db.createQuery("select max(kodemotor) from motor");
                        if (db.getResult().next()) {
                            String a = db.getResult().getString("max(kodemotor)");
                            String i = a.substring(5);
                            String e = String.valueOf(Integer.parseInt(i)+1);
                            
                            String q =String.valueOf(e);
                                if(q.length()==1){
                                    kodemotor.setText("MTR-000"+e);
                                }else if(q.length()==2){
                                    kodemotor.setText("MTR-00"+e);
                                }else if(q.length()==3){
                                    kodemotor.setText("MTR-0"+e);
                                }else if(q.length()==4){
                                    kodemotor.setText("MTR-"+e);
                                }
                        }else{
                            
                        }
                    }else{
                        kodemotor.setText("MTR-0001");
                }
                    db.closeResult();
                    db.closeConnection();
            }catch(Exception es){
                System.out.println(es);
            }
    }
    
    private void datamotor() {
        String[] judul={"Kode Motor","Merk Motor","Nama Motor","Warna","Harga","Jumlah"}; 
        DefaultTableModel tabModel = new DefaultTableModel (null,judul);
            try {
                DB db = new DB ("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
                db.createQuery("Select * from motor order by kodemotor");
                while (db.getResult().next()) {
                    String kodemotorr = db.getResult().getString("kodemotor");
                    String merk = db.getResult().getString("merk");
                    String namamotor = db.getResult().getString("namamotor");
                    String warna_m = db.getResult().getString("warna");
                    String harga_m = db.getResult().getString("harga");
                    String jumlah_m = db.getResult().getString("jumlah");
            
                    Object[] data = {kodemotorr,merk,namamotor,warna_m,harga_m,jumlah_m};
                    tabModel.addRow(data);
                    //getAutoKodePelanggan();
                }
                db.closeResult();
                db.closeConnection();
        
                tablemotor.setModel(tabModel);
                tablemotor.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD, 12));
                tablemotor.getTableHeader().setOpaque(false);
                tablemotor.getTableHeader().setBackground(new Color(251,253,138));
                tablemotor.setRowHeight(25);
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment(JLabel.CENTER);
                for(int a=0;a<tablemotor.getColumnCount();a++){
                    tablemotor.getColumnModel().getColumn(a).setCellRenderer(centerRenderer);
                }
                scrolldatamotor.getViewport().add(tablemotor);
                scrolldatamotor.setViewportView(tablemotor);
                }
                catch (Exception ex) {
                     System.out.println(ex); 
                }
    }
    
    
    void refresh(){
        kodemotor.setText("MTR-");
        nmmotor.setText("");
        cbmerk.setSelectedIndex(0);
        warna.setText("");
        harga.setText("");
        jumlah.setText("");
        txtcari.setText("");
        txttambah.setText("");
        jmlstok.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit = new model.KButton();
        hapus = new model.KButton();
        refresh = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        kGradientPanel2 = new model.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nmmotor = new javax.swing.JTextField();
        warna = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbmerk = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        simpan = new model.KButton();
        kodemotor = new javax.swing.JLabel();
        kGradientPanel1 = new model.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        scrolldatamotor = new javax.swing.JScrollPane();
        tablemotor = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txttambah = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jmlstok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 105, 114));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(251, 253, 138));
        kGradientPanel2.setkStartColor(new java.awt.Color(135, 223, 214));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setText("WARNA");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setText("HARGA");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setText("Rp.");

        cbmerk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yamaha", "Honda", "Suzuki", "Kawasaki" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("KODE MOTOR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("NAMA MOTOR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setText("MERK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("JUMLAH");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        kodemotor.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        kodemotor.setText("MTR-");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(kodemotor)
                        .addGap(140, 140, 140)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(cbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55)
                        .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(nmmotor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(cbmerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(kodemotor)))
                .addGap(22, 22, 22)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nmmotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(1, 169, 180));
        kGradientPanel1.setkStartColor(new java.awt.Color(135, 223, 214));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DATA MOTOR");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablemotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablemotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablemotorMouseClicked(evt);
            }
        });
        scrolldatamotor.setViewportView(tablemotor);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TAMBAH STOK MOTOR");

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JUMLAH STOK MOTOR");

        jmlstok.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jmlstok.setForeground(new java.awt.Color(255, 255, 255));
        jmlstok.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrolldatamotor)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jmlstok, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cari)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(refresh)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(scrolldatamotor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tambah)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlstok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
                DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
                db.createUpdate("update motor set "
                        + "merk='"+cbmerk.getSelectedItem()+"',"
                        + "namamotor='"+nmmotor.getText()+"',"
                        + "warna='"+warna.getText()+"',"
                        + "harga='"+harga.getText()+"',"
                        + "jumlah='"+jumlah.getText()+"'"
                        + "where kodemotor='"+kodemotor.getText()+"'");
                String pesan = ("Data Motor " +kodemotor.getText()+ " Berhasil diedit! ");
                JOptionPane.showMessageDialog(kGradientPanel1, pesan);
                //getAutoKodePelanggan();
                datamotor();
                refresh();
                db.closeResult();
                db.closeConnection();
            }
            catch (Exception se) {
                System.out.println(se);
            }
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
    DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
    db.createUpdate("insert into motor(kodemotor,merk,namamotor,warna,harga,jumlah,gambar)"
            +"values('"+kodemotor.getText()+"','"+cbmerk.getSelectedItem()+"','"+nmmotor.getText()+"','"+warna.getText()+"','"+harga.getText()+"','"+jumlah.getText()+"','')");
    String pesan = ("Data Motor " +kodemotor.getText()+ " Telah Tersimpan");
    JOptionPane.showMessageDialog(kGradientPanel1, pesan);
    //getAutoKodePelanggan();
    datamotor();
    db.closeResult();
    db.closeConnection();
    }
    catch (Exception se) {
        System.out.println(se);
    }
    }//GEN-LAST:event_simpanActionPerformed

    private void tablemotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablemotorMouseClicked
        Object n = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 0);
        Object o = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 1);
        Object p = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 2);
        Object q = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 3);
        Object r = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 4);
        Object s = tablemotor.getModel().getValueAt(tablemotor.getSelectedRow(), 5);

        kodemotor.setText(n.toString());
        cbmerk.setSelectedItem(o.toString());
        nmmotor.setText(p.toString());
        warna.setText(q.toString());
        harga.setText(r.toString());
        jumlah.setText(s.toString());
        jmlstok.setText(s.toString());
        //stok.setText(s.toString());
        //hitungstok.setText(s.toString());
        datamotor();
        txtcari.setText("");
        //txttambah.show();
        //stokmotor.show();
        //btntambah.show();
        
    }//GEN-LAST:event_tablemotorMouseClicked

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        refresh();
        datamotor();
        getAutoKode();
    }//GEN-LAST:event_refreshActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        try {
            DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
            db.createUpdate("Delete from motor where kodemotor = '"+kodemotor.getText()+"'");
            String pesan = (" Data Motor " +kodemotor.getText()+ " Telah Dihapus ");
            JOptionPane.showMessageDialog(kGradientPanel1, pesan);
            db.closeResult();
            db.closeConnection();
            datamotor();
            refresh();
        }catch (Exception se){
            System.out.println(se);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        String[] judul={"Kode Motor","Merk Motor","Nama Motor","Warna","Harga","Jumlah"}; 
        DefaultTableModel tabModel = new DefaultTableModel (null,judul);
        try {
                DB db = new DB("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
                db.createQuery("select * from motor where "
                        + "namamotor like '%"+txtcari.getText()+"%'"
                        + "OR merk like '%"+txtcari.getText()+"%'"
                        + "OR warna like '%"+txtcari.getText()+"%'"
                        + "OR harga like '%"+txtcari.getText()+"%'"
                        + "OR jumlah like'%"+txtcari.getText()+"%'"
                        + "OR kodemotor like '%"+txtcari.getText()+"%'");
                while (db.getResult().next()) {
                    String kodemotor_m = db.getResult().getString("kodemotor");
                    String merk_m = db.getResult().getString("merk");
                    String namamotor = db.getResult().getString("namamotor");
                    String warna_m = db.getResult().getString("warna");
                    String harga_m = db.getResult().getString("harga");
                    String jumlah_m = db.getResult().getString("jumlah");
            
                    Object[] data = {kodemotor_m,merk_m,namamotor,warna_m,harga_m,jumlah_m};
                    tabModel.addRow(data);
                }
                
                tablemotor.setModel(tabModel);
                scrolldatamotor.getViewport().add(tablemotor);
                scrolldatamotor.setViewportView(tablemotor);
                //datapelanggan();
                //refresh();
                db.closeResult();
                db.closeConnection();
            }
            catch (Exception se) {
                System.out.println(se);
            }
    }//GEN-LAST:event_cariActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try {
            String a = String.valueOf(Integer.parseInt(txttambah.getText().replaceAll(",", ""))+Integer.parseInt(jumlah.getText()));
            
            DB db = new DB ("jdbc:mysql://localhost:3306/kredit_km?user=root&password=");
            db.createUpdate("update motor set jumlah = '"+a+"' where kodemotor = '"+kodemotor.getText()+"'");
            String pesan = "Stok Berhasil Ditambah";
            JOptionPane.showMessageDialog(kGradientPanel1, pesan);
        
            db.closeResult();
            db.closeConnection();
             
        }catch (Exception e) {
            System.out.println(e);
        }
            datamotor();
            refresh();
    }//GEN-LAST:event_tambahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cbmerk;
    private model.KButton edit;
    private model.KButton hapus;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jmlstok;
    private javax.swing.JTextField jumlah;
    private model.KGradientPanel kGradientPanel1;
    private model.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel kodemotor;
    private javax.swing.JTextField nmmotor;
    private javax.swing.JButton refresh;
    private javax.swing.JScrollPane scrolldatamotor;
    private model.KButton simpan;
    private javax.swing.JTable tablemotor;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txttambah;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
